// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: internal/pb/settings/settings.proto

package settings_pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateBatCaveSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID       string `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	DeepSleepDelay int32  `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *CreateBatCaveSettingRequest) Reset() {
	*x = CreateBatCaveSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_settings_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatCaveSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatCaveSettingRequest) ProtoMessage() {}

func (x *CreateBatCaveSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_settings_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatCaveSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateBatCaveSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_settings_settings_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBatCaveSettingRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *CreateBatCaveSettingRequest) GetDeepSleepDelay() int32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type CreateBatCaveSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID       string `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	DeepSleepDelay int32  `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *CreateBatCaveSettingResponse) Reset() {
	*x = CreateBatCaveSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_settings_settings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatCaveSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatCaveSettingResponse) ProtoMessage() {}

func (x *CreateBatCaveSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_settings_settings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatCaveSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateBatCaveSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_settings_settings_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBatCaveSettingResponse) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *CreateBatCaveSettingResponse) GetDeepSleepDelay() int32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type GetBatCaveSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID string `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
}

func (x *GetBatCaveSettingRequest) Reset() {
	*x = GetBatCaveSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_settings_settings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatCaveSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatCaveSettingRequest) ProtoMessage() {}

func (x *GetBatCaveSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_settings_settings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatCaveSettingRequest.ProtoReflect.Descriptor instead.
func (*GetBatCaveSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_settings_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatCaveSettingRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type GetBatCaveSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID       string `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	DeepSleepDelay int32  `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *GetBatCaveSettingResponse) Reset() {
	*x = GetBatCaveSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_settings_settings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatCaveSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatCaveSettingResponse) ProtoMessage() {}

func (x *GetBatCaveSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_settings_settings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatCaveSettingResponse.ProtoReflect.Descriptor instead.
func (*GetBatCaveSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_settings_settings_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatCaveSettingResponse) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *GetBatCaveSettingResponse) GetDeepSleepDelay() int32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type UpdateBatCaveSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID       string `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	DeepSleepDelay int32  `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *UpdateBatCaveSettingRequest) Reset() {
	*x = UpdateBatCaveSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_settings_settings_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBatCaveSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatCaveSettingRequest) ProtoMessage() {}

func (x *UpdateBatCaveSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_settings_settings_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatCaveSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBatCaveSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_settings_settings_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBatCaveSettingRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *UpdateBatCaveSettingRequest) GetDeepSleepDelay() int32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type UpdateBatCaveSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceID       string `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	DeepSleepDelay int32  `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *UpdateBatCaveSettingResponse) Reset() {
	*x = UpdateBatCaveSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_settings_settings_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBatCaveSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatCaveSettingResponse) ProtoMessage() {}

func (x *UpdateBatCaveSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_settings_settings_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatCaveSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBatCaveSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_settings_settings_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBatCaveSettingResponse) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *UpdateBatCaveSettingResponse) GetDeepSleepDelay() int32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

var File_internal_pb_settings_settings_proto protoreflect.FileDescriptor

var file_internal_pb_settings_settings_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f,
	0x70, 0x62, 0x22, 0x61, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43,
	0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a,
	0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x62, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65,
	0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53,
	0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x36, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x22, 0x5f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65,
	0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x22, 0x61, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43,
	0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a,
	0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x62, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65,
	0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53,
	0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x32, 0xcf, 0x02, 0x0a, 0x0f, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x25, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b,
	0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61,
	0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x3b, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_settings_settings_proto_rawDescOnce sync.Once
	file_internal_pb_settings_settings_proto_rawDescData = file_internal_pb_settings_settings_proto_rawDesc
)

func file_internal_pb_settings_settings_proto_rawDescGZIP() []byte {
	file_internal_pb_settings_settings_proto_rawDescOnce.Do(func() {
		file_internal_pb_settings_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_settings_settings_proto_rawDescData)
	})
	return file_internal_pb_settings_settings_proto_rawDescData
}

var file_internal_pb_settings_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pb_settings_settings_proto_goTypes = []interface{}{
	(*CreateBatCaveSettingRequest)(nil),  // 0: settings_pb.CreateBatCaveSettingRequest
	(*CreateBatCaveSettingResponse)(nil), // 1: settings_pb.CreateBatCaveSettingResponse
	(*GetBatCaveSettingRequest)(nil),     // 2: settings_pb.GetBatCaveSettingRequest
	(*GetBatCaveSettingResponse)(nil),    // 3: settings_pb.GetBatCaveSettingResponse
	(*UpdateBatCaveSettingRequest)(nil),  // 4: settings_pb.UpdateBatCaveSettingRequest
	(*UpdateBatCaveSettingResponse)(nil), // 5: settings_pb.UpdateBatCaveSettingResponse
}
var file_internal_pb_settings_settings_proto_depIdxs = []int32{
	0, // 0: settings_pb.SettingsService.CreateBatCaveSetting:input_type -> settings_pb.CreateBatCaveSettingRequest
	2, // 1: settings_pb.SettingsService.GetBatCaveSetting:input_type -> settings_pb.GetBatCaveSettingRequest
	4, // 2: settings_pb.SettingsService.UpdateBatCaveSetting:input_type -> settings_pb.UpdateBatCaveSettingRequest
	1, // 3: settings_pb.SettingsService.CreateBatCaveSetting:output_type -> settings_pb.CreateBatCaveSettingResponse
	3, // 4: settings_pb.SettingsService.GetBatCaveSetting:output_type -> settings_pb.GetBatCaveSettingResponse
	5, // 5: settings_pb.SettingsService.UpdateBatCaveSetting:output_type -> settings_pb.UpdateBatCaveSettingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_settings_settings_proto_init() }
func file_internal_pb_settings_settings_proto_init() {
	if File_internal_pb_settings_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_settings_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatCaveSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_settings_settings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatCaveSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_settings_settings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatCaveSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_settings_settings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatCaveSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_settings_settings_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBatCaveSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_settings_settings_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBatCaveSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_settings_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_settings_settings_proto_goTypes,
		DependencyIndexes: file_internal_pb_settings_settings_proto_depIdxs,
		MessageInfos:      file_internal_pb_settings_settings_proto_msgTypes,
	}.Build()
	File_internal_pb_settings_settings_proto = out.File
	file_internal_pb_settings_settings_proto_rawDesc = nil
	file_internal_pb_settings_settings_proto_goTypes = nil
	file_internal_pb_settings_settings_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SettingsServiceClient is the client API for SettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettingsServiceClient interface {
	CreateBatCaveSetting(ctx context.Context, in *CreateBatCaveSettingRequest, opts ...grpc.CallOption) (*CreateBatCaveSettingResponse, error)
	GetBatCaveSetting(ctx context.Context, in *GetBatCaveSettingRequest, opts ...grpc.CallOption) (*GetBatCaveSettingResponse, error)
	UpdateBatCaveSetting(ctx context.Context, in *UpdateBatCaveSettingRequest, opts ...grpc.CallOption) (*UpdateBatCaveSettingResponse, error)
}

type settingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsServiceClient(cc grpc.ClientConnInterface) SettingsServiceClient {
	return &settingsServiceClient{cc}
}

func (c *settingsServiceClient) CreateBatCaveSetting(ctx context.Context, in *CreateBatCaveSettingRequest, opts ...grpc.CallOption) (*CreateBatCaveSettingResponse, error) {
	out := new(CreateBatCaveSettingResponse)
	err := c.cc.Invoke(ctx, "/settings_pb.SettingsService/CreateBatCaveSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) GetBatCaveSetting(ctx context.Context, in *GetBatCaveSettingRequest, opts ...grpc.CallOption) (*GetBatCaveSettingResponse, error) {
	out := new(GetBatCaveSettingResponse)
	err := c.cc.Invoke(ctx, "/settings_pb.SettingsService/GetBatCaveSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) UpdateBatCaveSetting(ctx context.Context, in *UpdateBatCaveSettingRequest, opts ...grpc.CallOption) (*UpdateBatCaveSettingResponse, error) {
	out := new(UpdateBatCaveSettingResponse)
	err := c.cc.Invoke(ctx, "/settings_pb.SettingsService/UpdateBatCaveSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServiceServer is the server API for SettingsService service.
type SettingsServiceServer interface {
	CreateBatCaveSetting(context.Context, *CreateBatCaveSettingRequest) (*CreateBatCaveSettingResponse, error)
	GetBatCaveSetting(context.Context, *GetBatCaveSettingRequest) (*GetBatCaveSettingResponse, error)
	UpdateBatCaveSetting(context.Context, *UpdateBatCaveSettingRequest) (*UpdateBatCaveSettingResponse, error)
}

// UnimplementedSettingsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSettingsServiceServer struct {
}

func (*UnimplementedSettingsServiceServer) CreateBatCaveSetting(context.Context, *CreateBatCaveSettingRequest) (*CreateBatCaveSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBatCaveSetting not implemented")
}
func (*UnimplementedSettingsServiceServer) GetBatCaveSetting(context.Context, *GetBatCaveSettingRequest) (*GetBatCaveSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatCaveSetting not implemented")
}
func (*UnimplementedSettingsServiceServer) UpdateBatCaveSetting(context.Context, *UpdateBatCaveSettingRequest) (*UpdateBatCaveSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatCaveSetting not implemented")
}

func RegisterSettingsServiceServer(s *grpc.Server, srv SettingsServiceServer) {
	s.RegisterService(&_SettingsService_serviceDesc, srv)
}

func _SettingsService_CreateBatCaveSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBatCaveSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).CreateBatCaveSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settings_pb.SettingsService/CreateBatCaveSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).CreateBatCaveSetting(ctx, req.(*CreateBatCaveSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_GetBatCaveSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatCaveSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetBatCaveSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settings_pb.SettingsService/GetBatCaveSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetBatCaveSetting(ctx, req.(*GetBatCaveSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_UpdateBatCaveSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatCaveSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).UpdateBatCaveSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settings_pb.SettingsService/UpdateBatCaveSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).UpdateBatCaveSetting(ctx, req.(*UpdateBatCaveSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SettingsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "settings_pb.SettingsService",
	HandlerType: (*SettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBatCaveSetting",
			Handler:    _SettingsService_CreateBatCaveSetting_Handler,
		},
		{
			MethodName: "GetBatCaveSetting",
			Handler:    _SettingsService_GetBatCaveSetting_Handler,
		},
		{
			MethodName: "UpdateBatCaveSetting",
			Handler:    _SettingsService_UpdateBatCaveSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/settings/settings.proto",
}
