// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pb/settings/settings.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)
